services:
  cadmus-graph-studio-api:
    container_name: cadmus-graph-studio-api
    image: vedph2020/cadmus-graph-studio-api:0.0.9
    ports:
      - 5257:8080
    networks:
      - cadmus-graph-studio-network

networks:
  cadmus-graph-studio-network:
    driver: bridge
